### ISSUE TITLE
【question】Sermant在增强类时，如果抛出异常，期望输出日志到文件

### ISSUE THREAD

**Issue by SNAIL-0011** [sermant-io/Sermant#1081]
### What would you like to be added?

Sermant增强类失败时，期望输出日志到文件。（日志信息包括：被增强的类名、失败原因等等）

### Why is this needed?

便于快速分析问题。

我在使用Sermant开发Agent时，发现程序没有按预期执行，调试过程中，发现sermant-agentcore-core-0.6.2.jar包中AgentBuilder类的transform方法抛出了异常：java.lang.NoClassDefFoundError，解决后，程序才正常执行。
期望在增强类失败时，能够输出日志到文件，方便排查问题。

**Comment by luanwenfei-venus** [comment]
在config.properties下添加agent.config.isShowEnhanceLogEnable=true，ByteBuddy的增强日志将输出在日志文件中

**Comment by luanwenfei-venus** [comment]
ByteBuddy中出现的错误，ByteBuddy框架本身会进行捕获，并不能将异常抛出，开启上述开关，可以获取到ByteBuddy捕获错误后给出的提示信息

**Comment by SNAIL-0011** [comment]
> 在config.properties下添加agent.config.isShowEnhanceLogEnable=true，ByteBuddy的增强日志将输出在日志文件中

方案亲测有效，对定位问题有帮助，谢谢~

**Comment by SNAIL-0011** [comment]
> 在config.properties下添加agent.config.isShowEnhanceLogEnable=true，ByteBuddy的增强日志将输出在日志文件中

开启该配置，当类增强失败时，能搜索到1条ERROR日志，显示类增强失败，但是没有异常原因，能不能打关键异常信息也打印出来？
