### ISSUE TITLE
为什么设计插件主模块和插件服务模块

### ISSUE THREAD

**Issue by purekeeper** [sermant-io/Sermant#1216]
### What do you want to ask?

为什么设计插件主模块和插件服务模块？以及插件主模块用appclassloader加载，插件服务模块用自定义加载器加载？如果插件主模块和插件服务模块合并成一个模块直接用自定义加载器加载会有什么问题呢？只是觉得你们设计的插件主模块和插件服务模块使用起来有点复杂，是出于什么考虑呢？

**Comment by lilai23** [comment]
插件主模块中拦截器做拦截的时候会涉及到业务应用的依赖（在pom中以provided方式引入），当前方案以appclassloader加载，在插件主模块中不能引入第三方依赖，因为可能导致和业务应用出现相同类的不同版本产生类冲突，从而我们衍生出了插件服务模块，如果有第三方依赖都只能在插件服务模块中引入。
