### ISSUE TITLE
According to sermant official documentation, configuring traffic tags does not take effect.

### ISSUE THREAD

**Issue by BigG-King** [sermant-io/Sermant#1237]
### What happened?

According to sermant official documentation, configuring traffic tags does not take effect.

### How can we reproduce it (as minimally and precisely as possible)?

The current online environment in Shanghai is sermant version 0.5.1. The project uses nacos as the registration center and sermant for management. Traffic markers are configured according to the official document below.

https://sermant.io/zh/document/plugin/flowcontrol.html#%E8%AF%A6%E7%BB%86%E6%B2%BB%E7%90%86%E8%A7%84%E5 %88%99
![image](https://github.com/huaweicloud/Sermant/assets/70269305/761661ea-d9ee-4b87-8a85-9a71c0747580)

### Anything else we need to know?
According to sermant official documentation, configuring traffic tags does not take effect. You need to change servicecomb.MatchGroup to servicecomb.**m**atchGroup.

### Sermant version

<details>
0.5.1
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```
</details>

**Comment by luanwenfei-venus** [comment]
文档已做修改，问题是否已解决，如已解决，issue将会关闭

**Comment by luanwenfei-venus** [comment]
无进展更新，关闭issue
