### ISSUE TITLE
Dubbo2.7.15 uses sermant1.0.3 to configure fault tolerance and retry does not take effect

### ISSUE THREAD

**Issue by cl-4021** [sermant-io/Sermant#1246]
### What happened?

Use dynamic configuration to implement fault-tolerant retry. Configure traffic tags and retry strategies according to the sermant official website. You can see that there are no errors in the configuration log and the strategy is issued normally. There are two identical provider instances in my project, and one access will throw An exception occurs, and the other is normal access. After turning on the fault tolerance strategy, the correct result should be returned every time, but the result is that you will still see the exception page.

### How can we reproduce it (as minimally and precisely as possible)?

Dubbo2.7.15 can be reproduced by using cse dynamic configuration to issue a fault-tolerant retry strategy

### Sermant version

<details>

</details>
sermant1.0.3

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```
</details>

**Comment by TangLeDaily** [comment]
The problem has been solved. Please pay attention to the path configuration format of sermant traffic tag. The issue will be closed.
