### ISSUE TITLE
Dubbo2.7.15 uses sermant1.0.3 dynamic configuration to implement error injection does not work.

### ISSUE THREAD

**Issue by cl-4021** [sermant-io/Sermant#1247]
### What happened?

Configure the error injection traffic mark and error injection policy according to the sermant official website documentation. No errors are reported when viewing the logs on the cce cluster management page. After the error injection policy is enabled, the targeted interface can still be accessed normally.

### How can we reproduce it (as minimally and precisely as possible)?

Dubbo2.7.15 can be reproduced using error injection strategy

### Sermant version

<details>

</details>
sermant1.0.3
dubbo2.7.15

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```
</details>

**Comment by TangLeDaily** [comment]
Error injection requires mounting the sermant on the client that initiates the request. For example, mounting it on the consumer of dubbo will intercept the request sent by the consumer to the provider (but will not intercept the request sent to the consumer by postman, for example. In this case，the consumer acts as a server and error injection will not take effect). May I ask if sermant was mounted when you initiated the request to use the service?

**Comment by cl-4021** [comment]
The consumer has mounted sermant. When the consumer starts in the cce container, it accesses cse through sermant.



---The original message---
Sender: ***@***.***&gt;
Sent time: July 18, 2023 (Tuesday) 10:52 am
Recipient: ***@***.***&gt;;
CC: ***@***.******@***.***&gt;;
Topic: Re: [huaweicloud/Sermant] Error injection using sermant1.0.3 dynamic configuration in dubbo2.7.15 does not take effect (Issue #1247)




 
Error injection requires mounting the sermant on the client that initiates the request, such as mounting it on the consumer of dubbo, which will intercept requests sent by the consumer to the provider (but will not intercept requests sent to the consumer using postman, for example). May I ask if sermant was mounted when you initiated the request to use the service?

**Comment by TangLeDaily** [comment]
After the consumer mounts sermant, error injection will take effect on requests sent by the consumer, but not on requests received. For example, when postman is used to send requests to the consumer, in which case the consumer acts as a server and error injection will not take effect. In the problem scenario, is the request sent by the cosumer failed to be intercepted and take effect?

**Comment by TangLeDaily** [comment]
The problem has been solved. Please pay attention to the path configuration format of sermant traffic tag. The issue will be closed.
