### ISSUE TITLE
Support the governance capabilities of gateway calling services

### ISSUE THREAD

**Issue by BigG-King** [sermant-io/Sermant#1248]
### What would you like to be added?

Hope to support the governance capability of calling services through gateway.
1.sermant1.0.3, the gateway calls the mall4cloud-search service and configures the label routing of the search service. The label routing does not take effect.
servicecomb.routeRule.mall4cloud-search
- precedence: 1
  route:
    -tags:
        version: 1.0.1
      weight: 100

2.sermant1.0.3, gateway calls mall4cloud-search service, downgrade (error injection) configuration does not take effect
3.sermant1.0.3, gateway calls mall4cloud-search service, fault tolerance retry configured through cse page does not take effect
4.sermant1.0.3, gateway calls mall4cloud-search service, load balancing does not take effect

The project structure is as follows:
The front end calls -gateway- to call the mall4cloud-search service, where gateway is the gateway service. Is a separate microservice.

### Why is this needed?

Increase the ability of sermant

**Comment by luanwenfei-venus** [comment]
Sermant does not have version 1.0.9. Can you describe the open source version again?

**Comment by provenceee** [comment]
> Sermant does not have version 1.0.9. Can you describe the open source version again?

Modified to 1.0.3

**Comment by luanwenfei-venus** [comment]
> > Sermant does not have version 1.0.9. Can you describe the open source version again?
>
> Modified to 1.0.3

What language and framework service is gateway?

**Comment by provenceee** [comment]
> > > Sermant does not have version 1.0.9. Can you describe the open source version again?
>>
>>
> > Modified to 1.0.3
>
> What language and framework service is gateway?

spring cloud gateway

**Comment by BigG-King** [comment]
Just to confirm, the governance capabilities I mentioned are not currently supported by us?

**Comment by BigG-King** [comment]
插件还是sermant1.0.3的版本，没有新版本的插件，没有办法验证。请提供新版本的sermant插件
