### ISSUE TITLE
When developing a plugin, is it possible to intercept methods in the parent class of the target class?

### ISSUE THREAD

**Issue by likui63** [sermant-io/Sermant#1371]
### What do you want to ask?

When developing a plug-in, is it possible to intercept methods in the parent class of the target class?
For example: When I wanted to recommend the createRquest() method of the RestTemplate class in Spring, I found that the recommendation was unsuccessful. The method was declared in the parent class, but there is no problem with methods like doExecute().

**Comment by luanwenfei-venus** [comment]
Can you elaborate the information about this createRequest() in detail, which version of spring it is, which parent class it belongs to, and is this createRequest an Abstract method?

**Comment by likui63** [comment]
My main purpose is to add custom parameters to the http request header when calling RestTemplate
Spring version: 5.3.30
The relationship between classes is as follows:
public class RestTemplate extends InterceptingHttpAccessor implements RestOperations
public abstract class InterceptingHttpAccessor extends HttpAccessor
Function: createRequest() is a protected non-abstract method defined in the HttpAccessor class, mainly to create a ClientHttpRequest object
                                                                                                                                                                                                       
In Skywalking, you can createRequest() of the RestTemplate parent class, but during the plug-in development process using Sermant, I found that the createRequest() method cannot be intercepted, but the doExceute() method declared in the RestTemplate class can be intercepted.

**Comment by hanbingleixue** [comment]
@lkjust08 Hello, Sermant currently does not support bytecode enhancement for methods of parent classes inherited by the target class. If you need to enhance the bytecode of the parent class's method, it is recommended that you intercept the parent class's method to implement it. For example, you can directly intercept the createRequest method of HttpAccessor to implement it.

**Comment by hanbingleixue** [comment]
The question has been answered. No more questions will be raised. Therefore, this issue is closed.
