### ISSUE TITLE
Can Sermant support Prometheus monitoring?

### ISSUE THREAD

**Issue by zwmagic** [sermant-io/Sermant#1445]
### What would you like to be added?

It is hoped that Sermant will support Prometheus monitoring so that Sermant's core metrics as well as each plugin's custom metrics can be monitored through Grafana.

### Why is this needed?

1. Through integration with Grafana, we can use its rich data visualization capabilities to create intuitive dashboards that can help us quickly locate and solve problems.
2. Through monitoring metrics, monitoring alarms can be added to ensure the stability of sermant.

###Proposal proposal
Regarding the need for Sermant to support Prometheus monitoring, I am currently considering the following three options and hope to discuss them in the community in order to choose the most suitable one or combine it with other more suitable options.
#### Solution 1: Integrate Micrometer
Advantages: Micrometer provides a common interface integrated with a variety of monitoring systems (including Prometheus), has complete documentation, and is easy to get started.
Disadvantages: need to introduce additional dependencies

#### Option 2: Use Prometheus’ native API directly
Advantages: Directly use Prometheus native capabilities
Disadvantages: Completely bound to Prometheus

#### Option 3: Implement custom Metric interface
advantage:
- Provides a flexible and scalable way to customize metrics, easy to implement and maintain
- Compatible with a variety of surveillance systems

shortcoming:
- Additional code needs to be developed to handle indicator registration and exposure
- It may take time for the community to adapt to this new interface

**Comment by hanbingleixue** [comment]
Currently, the monitoring plug-in supports reporting metrics to Prometheus. The monitoring plugin also supports reporting the metrics information collected by the flow control plugin. You can check the user manual of the monitoring plug-in to see if it meets your requirements. Monitoring plugin manual address: https://sermant.io/zh/document/plugin/monitor.html.

**Comment by zwmagic** [comment]
Prometheus metrics capabilities can be transferred to core, so that other plugins can also customize metrics.

**Comment by hanbingleixue** [comment]
目前其他插件也是可以自定义指标，流控插件就是自定义的熔断相关的指标，只不过依赖于监控插件进行上报。core主要是提供核心能力，如果太多东西下沉到core，core会变的太重。

**Comment by daizhenyu** [comment]
The Sermant community accepted this issue request and will support Prometheus in monitoring the metrics information of the Sermant framework, plugins, and host microservices in the future.
