### ISSUE TITLE
What is different between the InstanceIsolationRequestHandler and CircuitBreakerRequestHandler

### ISSUE THREAD

**Issue by longweiwork** [sermant-io/Sermant#1456]
### What do you want to ask?

When I add some circuitbreaker config and trigger fuse, the InstanceIsolationRequestHandler will intercept request and return  InstanceIsolationException, but I want to return CircuitBreakerException, so what should I do to meet my expectations. Looking forward to your answer, thanks~

**Comment by hanbingleixue** [comment]
The instance isolation priority is greater than the circuit breaker priority, so the InstanceIsolation RequestHandler intercepts the request and ultimately returns an InstanceIsolation Exception. Therefore, it is currently not supported to modify the returned exception to a Circuit BreakerException through configuration or other means.

**Comment by hanbingleixue** [comment]
The question has been answered. No more questions will be raised. Therefore, this issue is closed.
