### ISSUE TITLE
Unable to make protected java.lang.Object java.lang.ClassLoader.getClassLoadingLock(java.lang.String) accessible: module java.base does not "opens java.lang" to unnamed module

### ISSUE THREAD

**Issue by PerforMance308** [sermant-io/Sermant#1511]
### What do you want to ask?

I was trying to use sermant-injector in K8S, and I get this error:

![image](https://github.com/sermant-io/Sermant/assets/12728232/e948aa0e-529b-4759-be99-35268bf160e6)

**Sermant sersion:** 1.4.0

any ideas?

**Comment by lilai23** [comment]
you can try to add follow VM commands：
--add-opens java.base/java.lang=ALL-UNNAMED
--add-opens java.base/java.net=ALL-UNNAMED
--add-opens java.base/java.math=ALL-UNNAMED
--add-opens java.base/sun.net.www=ALL-UNNAMED
--add-opens java.base/sun.net.www.protocol.http=ALL-UNNAMED

**Comment by hanbingleixue** [comment]
The solution has been provided. No other questions are replied. Therefore, this issue is closed.
