### ISSUE TITLE
Why was C language chosen over Java for attach.c?

### ISSUE THREAD

**Issue by Yaxx19** [sermant-io/Sermant#1516]
### What do you want to ask?

Hello, I was looking at the [attach.c](https://github.com/sermant-io/Sermant/blob/develop/scripts/attach.c) script and I’m curious about the decision to implement it in C rather than Java. Could you please share the design considerations or trade-offs that led to this choice? Understanding the rationale behind the language selection would be very helpful for my own learning and to better appreciate the project’s architecture.

**Comment by hanbingleixue** [comment]
This script is developed when the Sermant interconnects with the Gopher. The Gopher supports the C language script. Therefore, the C language is used to dynamically mount the script.

**Comment by hanbingleixue** [comment]
The question has been answered. No other questions will be raised. Therefore, this issue is closed.
