### ISSUE TITLE
【求助】有什么方式可以将流量标签暴露给宿主应用

### ISSUE THREAD

**Issue by myqqai** [sermant-io/Sermant#1526]
### What do you want to ask?

我正在使用流量透传插件，请问有什么方式可以在宿主应用获取标签！

**Comment by hanbingleixue** [comment]
@myqqai  For the server, the tag information can be obtained from the HTTP header, Dubbo attachment, grpc metadata, and Kafka message header. For example, service A invokes service B through an HTTP request. When service B executes the service method of HttpServlet, the host application can obtain the tag information from the request header of HttpServletRequest.

**Comment by myqqai** [comment]
> @myqqai 对于服务端来说，要从HTTP header、Dubbo attachment、grpc metadata、Kafka message header中获取标签信息。例如服务A通过HTTP请求调用服务B，当服务B执行HttpServlet的service方法时，需要从机应用从HttpServletRequest的请求header中获取标签信息。

@hanbingleixue 感谢回复，是的这样是可以实现，但与流量透传插件实现功能是不是重复，需要针对HTTP header、Dubbo attachment 等做拦截，读取标签。我更倾向于在任何地方通过Threadlocal 获取。

**Comment by hanbingleixue** [comment]
@myqqai  You are advised to obtain the tag information from the HTTP header, Dubbo attachment, grpc metadata, and Kafka message header on the server. For example, for HttpServelet, add the processing logic to the interface on the server and obtain the tag information from the request header of HttpServletRequest. You are not advised to obtain tag information from threadLocals or inheritableThreadLocals of the server thread through reflection. If there's no other way， You can obtain the tag information from threadLocals or inheritableThreadLocals of the thread that processes the request on the server.

**Comment by hanbingleixue** [comment]
The solution has been provided. No follow-up problems. Therefore, this issue is closed.
