### ISSUE TITLE
ConfigSubscriber mode not support Map

### ISSUE THREAD

**Issue by HozonLee** [sermant-io/Sermant#1536]
### What happened?

When I use CommonGroupConfigSubscriber do config subscribe from nacos，Failed to assign the map type attribute in the configuration class、The content format in nacos has been changed

### How can we reproduce it (as minimally and precisely as possible)?

 definitionthe a map type attribute in the configuration class

### Sermant version

<details>
sermant version 1.3.0
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```
</details>

**Comment by lilai23** [comment]
It is caused by unnecessary process for config content. We will fix it in following version
