### ISSUE TITLE
SermantClassLoader设计咨询

### ISSUE THREAD

**Issue by JedrekWang** [sermant-io/Sermant#1595]
#### 现状
我对比了Sermant和OpenTelemetry关于JavaAgent ClassLoader隔离这块的实现
发现一点差异：OpenTelemetry通过将AgentClassLoader的parent设置为null，AgentClassLoader先从自己的classpath加载，加载不到从BootStrapClassLoader加载，来隔离JavaAgent和业务代码
但是Sermant的SermantClassLoader的parent为AppClassLoader，先从自己的classpath加载，加载不到走双亲委托加载(BootStrapClassLoader -> ExtClassLoader -> AppClassLoader流程)

#### 问题
麻烦咨询一下，SermantClassLoader为啥故意没有将parent设置为null，这样不是可以更好的隔离业务代码吗？还是说有基于其他考虑？感谢答复（应该不影响Sermant的PluginClassLoader，仍然可以通过localLoader机制直接获取宿主服务的类)

**Comment by hanbingleixue** [comment]
@JedrekWang This is to reuse the classes that have been loaded by the host application, ensuring that the SermantClassLoader does not need to be reloaded.

**Comment by hanbingleixue** [comment]
Question answered. No follow-up questions. Therefore, this issue is closed.
