### ISSUE TITLE
关于ClassInjectDefine中factoryName为空的问题

### ISSUE THREAD

**Issue by AYue-94** [sermant-io/Sermant#1596]
### What do you want to ask?

![image](https://github.com/user-attachments/assets/189e9cb6-2023-4c05-a666-be3e91858d3e)
1. 在低版本中，plugin中的类由appclassloader加载，为了使用springboot的接口需要用springboot类加载器加载；
2. 在高版本中，plugin中的类由pluginclassloader加载，pluginclassloader内部可以用线程类加载器加载到springboot的api；
高版本是否可以不用再声明factoryName为空的ClassInjectDefine？

**Comment by hanbingleixue** [comment]
@AYue-94 ClassInjectDefine is declared to ensure that these classes can be loaded through the class loader of the host. In later versions, ClassInjectDefine with empty factoryName also needs to be declared.

**Comment by AYue-94** [comment]
I try to remove ClassInjectDefine with empty factoryName, for example in dynamic-config-plugin.
![image](https://github.com/user-attachments/assets/a8fe18ad-7ec8-4e82-bc24-2c8c00ab3efe)
and the host springboot application can works well with dynamic-config-plugin.

for example:
1. springboot LaunchedURLClassLoader load SpringEnvironmentProcessor but fail. fallback, Sermant ClassLoaderLoadClassInterceptor use PluginClassLoader load SpringEnvironmentProcessor,  success;
3. when SpringEnvironmentProcessor new DynamicConfigPropertySource will use PluginClassLoader too,  its ok to find DynamicConfigPropertySource;
4. DynamicConfigPropertySource implement springboot EnumerablePropertySource interface,  EnumerablePropertySource is in LaunchedURLClassLoader, so PluginClassLoader fallback use thread context classloader load EnumerablePropertySource success；

so why need to declare DynamicConfigPropertySource in ClassInjectDefine with empty factoryName ? 
![image](https://github.com/user-attachments/assets/00c83b1b-4aec-4ffc-b59e-134c2cc28915)

**Comment by hanbingleixue** [comment]
@AYue-94 These classes are loaded by the host to shield the original configuration center of the host. If these classes are not declared, the host can run properly, but the functions are affected.

**Comment by AYue-94** [comment]
what does "functions are affected" mean? can you give me some example? I'm very confusion

**Comment by hanbingleixue** [comment]
@AYue-94 For example, the dynamic-config-plugin cannot shield the original configuration center after removing these declarations.

**Comment by hanbingleixue** [comment]
Answers have been provided, and no other questions are available. Therefore, this issue is closed.
