### ISSUE TITLE
store heartbeat use redis setex with wrong timeunit

### ISSUE THREAD

**Issue by AYue-94** [sermant-io/Sermant#1610]
### What happened?

max.effective.time=60000, the time unit is milliseconds.
![image](https://github.com/user-attachments/assets/7ef2bc38-e88d-4e69-98da-332b1db36597)
when store heartbeat use redis setex command, directly set ttl as 60000 seconds.
![image](https://github.com/user-attachments/assets/85df42ed-f32a-4ec4-a64e-67cb403f0e3a)

### How can we reproduce it (as minimally and precisely as possible)?

just start an agent to send heartbeat.

### Sermant version

2.0.0

### OS version

MacOS 14.1

**Comment by AYue-94** [comment]
i will try to fix it

**Comment by lilai23** [comment]
> i will try to fix it

Thanks for find and fix this issue

**Comment by lilai23** [comment]
@AYue-94 I have found you are not in our contributers now. Confirm your email of GitHub account is the same as your
email when you commit your codes. It may happen for this reason
