### ISSUE TITLE
Agentmain or Premain?

### ISSUE THREAD

**Issue by SunJiFengPlus** [sermant-io/Sermant#1662]
### What do you want to ask?

Which is the best way to use it?  Is there any difference between Agentmain and Premain? 

The [documentation](https://eclectic-belekoy-c6087a.netlify.app/zh/document/user-guide/sermant-agent.html#sermant-agent%E4%BD%BF%E7%94%A8%E6%89%8B%E5%86%8C) looks like the Agentmain is more flexible, and agent upgrades don't require restarting the java process, but the operation is more complex, are there any other differences? Such as compatibility or anything else.

**Comment by hanbingleixue** [comment]
Based on your application scenario, for example, if the service-registry plug-in needs to shield the original registration center, you need to use the premain to enhance the bytecode. When the service is started, cancel the registration of the original registration center. The agentmain function cannot be used.
