### ISSUE TITLE
DefaultAdviser logs are output to the application console

### ISSUE THREAD

**Issue by provenceee** [sermant-io/Sermant#1666]
### What happened?

DefaultAdviser logs are output to the application console

![20241112-191354](https://github.com/user-attachments/assets/66355249-9d11-4680-80c2-296b554c9610)

### How can we reproduce it (as minimally and precisely as possible)?

Using the sermant-flowcontrol plugin in the springboot3 environment

### Sermant version

<details>
2.x
</details>

### OS version

n/a

**Comment by hanbingleixue** [comment]
The code has been merged and will be released in later versions.
