### ISSUE TITLE
【bug】It will generate two interceptors when intercept the method which has it's super class

### ISSUE THREAD

**Issue by justforstudy-A** [sermant-io/Sermant#791]
### What happened?

It will generate two interceptors  when I intercept the method CloseableHttpClient#excute(HttpUriRequest) which has super type named HttpClient

### How can we reproduce it (as minimally and precisely as possible)?

N/A

### Sermant version

<details>
0.5.0
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```
</details>

**Comment by luanwenfei-venus** [comment]
find two CloseableHttpClient#excute(HttpUriRequest) but have different return type
