### ISSUE TITLE
【bug】When run in IDE, service-registry plugin occurs： java.lang.LinkageError.

### ISSUE THREAD

**Issue by luanwenfei-venus** [sermant-io/Sermant#798]
### What happened?

When run in IDE, service-registry plugin occurs：
java.lang.LinkageError: loader constraint violation: when resolving method "org.slf4j.impl.StaticLoggerBinder.getLoggerFactory()Lorg/slf4j/ILoggerFactory;" the class loader (instance of com/huaweicloud/sermant/core/plugin/classloader/PluginClassLoader) of the current class, org/slf4j/LoggerFactory, and the class loader (instance of sun/misc/Launcher$AppClassLoader) for the method's defining class, org/slf4j/impl/StaticLoggerBinder, have different Class objects for the type org/slf4j/ILoggerFactory used in the signature

### How can we reproduce it (as minimally and precisely as possible)?

Run service-registry plugin.

### Sermant version

<details>
0.5.0
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```
</details>

**Comment by lilai23** [comment]
If this issue occurs, add logback-classic to specific module of classloader. Like: SermantCloassloader->sermant-common or other jar placed under agent/common directory; PluginClassloader->plugin module;ServiceClassloader->service module
