### ISSUE TITLE
使用Sermant后，Spring Cloud OpenFeign依赖LB，熔断，限流等逻辑还会走吗？

### ISSUE THREAD

**Issue by SoftwareKing** [sermant-io/Sermant#842]
### What do you want to ask?

使用Sermant后，Spring Cloud OpenFeign依赖LB，熔断，限流等逻辑还会走吗？

**Comment by justforstudy-A** [comment]
> ### What do you want to ask?
> 使用Sermant后，Spring Cloud OpenFeign依赖LB，熔断，限流等逻辑还会走吗？

请问这里的熔断，限流等逻辑指的是sermant的能力，还是springcloud的第三方依赖

**Comment by SoftwareKing** [comment]
@justforstudy-A 是Spring Cloud的依赖,因为Agent劫持了,所以显得业务应用引入的就显的多余

**Comment by justforstudy-A** [comment]
> @justforstudy-A 是Spring Cloud的依赖,因为Agent劫持了,所以显得业务应用引入的就显的多余

sermant只会劫持请求的逻辑，原来的springcloud的熔断限流逻辑怎么走，sermant不会干预。只是两者最好不要同时开启，否则必然有触发的先后顺序问题。
而开启sermant的流控能力，需要在配置中心下发规则或者application.yml.
