### ISSUE TITLE
【bug】SpringCloud通过sermant接入CSE：负载启动报错

### ISSUE THREAD

**Issue by douju** [sermant-io/Sermant#948]
### What happened?

待改造项目[OCP](https://gitee.com/owenwangwen/open-capacity-platform/tree/master/)中服务编译构建+打包成镜像后，在CCE进行创建负载时出现错误，且并未注册到CSE，错误对应日志信息为：Caused by: java.lang.VerifyError: (class: org/springframework/cloud/openfeign/ribbon/LoadBalancerFeignClient$$EnhancerBySpringCGLIB$$fb2787d0, method: execute signature: (Lfeign/Request;Lfeign/Request$Options;)Lfeign/Response;) Incompatible object argument for function call

（用的是OCP开源项目主分支代码，其中的注册中心使用的Eureka）

### How can we reproduce it (as minimally and precisely as possible)?

可以把[OCP](https://gitee.com/owenwangwen/open-capacity-platform/tree/master/)代码拉下来，制作镜像后去CCE用sermant创建负载试下，如果要用DevCloud构建的话给pom文件中的repackage指定一下版本(可用2.1.6.RELEASE)，不然会构建失败。可以只打一个user-center镜像创建负载验证下能否注册到CSE。

### Sermant version

<details>
    0.5.1和0.4.4都会报这个错
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```
</details>

**Comment by provenceee** [comment]
目前分析是增强了cglib动态代理的类才导致的这个异常，所以core不再对代理类进行增强，从业务上分析，也不需要对代理类进行增强，因为代理类是宿主类的子类，会去调用父类方法，所以只要增强宿主类就行。
目前可在java -jar启动时，增加 -Xverify:none 参数规避该问题
